---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: envoyFilter configuration
templates:
  - base.yaml
values:
  - ../../../tests/overallValues.yaml
tests:
  - it: no envoyFilter by default
    asserts:
      - containsDocument:
          kind: EnvoyFilter
        not: true

  - it: envoyFilter can be disabled
    set:
      resources.envoyFilters.main.enabled: false
    asserts:
      - containsDocument:
          kind: envoyFilter
        not: true

  - it: enabled envoyFilter
    set:
      resources.envoyFilters.main:
        workloadLabels:
          app: test
        configPatches:
          - applyTo: CLUSTER
    documentSelector:
      path: kind
      value: EnvoyFilter
    asserts:
      - equal:
          path: metadata.name
          value: RELEASE-NAME
      - equal:
          path: spec.workloadSelector.labels.app
          value: test
      - equal:
          path: spec.configPatches
          value:
            - applyTo: CLUSTER


  - it: second envoyFilter can be set
    set:
      resources.envoyFilters:
        main:
          workloadLabels:
            app: test
        second:
          workloadLabels:
            app: test2
          configPatches:
            - applyTo: CLUSTER
    documentSelector:
      path: metadata.name
      value: RELEASE-NAME-second
    asserts:
      - isKind:
          of: EnvoyFilter
      - equal:
          path: spec.workloadSelector.labels.app
          value: test2
      - equal:
          path: spec.configPatches
          value:
            - applyTo: CLUSTER