---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: networkPolicy values
templates:
  - base.yaml
values:
  - ../../../tests/overallValues.yaml
tests:
  - it: main networkPolicy is disabled by default
    asserts:
      - containsDocument:
          kind: NetworkPolicy
        not: true

  - it: main networkPolicy can be enabled
    set:
      resources.networkPolicies:
        main:
          controller: yopla
          rules: {}
          policyTypes:
            - Ingress
    asserts:
      - documentSelector:
          path: kind
          value: NetworkPolicy
        equal:
          path: metadata.name
          value: RELEASE-NAME

  - it: networkPolicy targets supports custom podSelector
    set:
      resources.networkPolicies:
        main:
          enabled: true
          controller: main
          policyTypes:
            - Ingress
          rules: {}
          podSelector: {}
    documentSelector:
      path: kind
      value: NetworkPolicy
    asserts:
      - equal:
          path: spec.podSelector
          value: {}

  - it: networkPolicy rules are passed through
    set:
      resources.networkPolicies:
        main:
          enabled: true
          controller: main
          policyTypes:
            - Ingress
          rules:
            ingress:
              - {}
            egress:
              - {}
    documentSelector:
      path: kind
      value: NetworkPolicy
    asserts:
      - equal:
          path: spec.ingress
          value:
            - {}
      - equal:
          path: spec.egress
          value:
            - {}
