---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: imagePolicy configuration
templates:
  - base.yaml
values:
  - ../../../tests/overallValues.yaml
tests:
  - it: no imageRepository by default
    asserts:
      - containsDocument:
          kind: ImagePolicy
        not: true

  - it: imagePolicy can be disabled
    set:
      resources.imagePolicies.main.enabled: false
    asserts:
      - containsDocument:
          kind: ImagePolicy
        not: true

  - it: default enabled imagePolicy
    set:
      resources:
        imageRepositories:
          main:
            controllerContainer: main/main
        imagePolicies:
          main:
            imageRepository: main
    documentSelector:
      path: kind
      value: ImagePolicy
    asserts:
      - equal:
          path: metadata.name
          value: RELEASE-NAME-NAMESPACE
      - equal:
          path: metadata.namespace
          value: flux-system
      - equal:
          path: spec.imageRepositoryRef
          value:
            name: RELEASE-NAME
            namespace: NAMESPACE
      - equal:
          path: spec.policy.semver.range
          value: ^1.x.x-0
      - equal:
          path: metadata.labels.app
          value: RELEASE-NAME

  - it: imagePolicy with semverRange
    set:
      resources:
        imageRepositories:
          main:
            enabled: true
            controllerContainer: main/main
        imagePolicies:
          main:
            imageRepository: main
            semverRange: "42"
    documentSelector:
      path: kind
      value: ImagePolicy
    asserts:
      - equal:
          path: spec.policy.semver.range
          value: 42

  - it: second imagePolicy can be set
    set:
      resources:
        imageRepositories:
          main:
            enabled: true
            controllerContainer: main/main
        imagePolicies:
          main:
            imageRepository: main
          second:
            imageRepository: main

    documentSelector:
      path: metadata.name
      value: RELEASE-NAME-second-NAMESPACE
    asserts:
      - isKind:
          of: ImagePolicy
      - equal:
          path: spec.policy.semver.range
          value: ^1.x.x-0
      - equal:
          path: spec.imageRepositoryRef
          value:
            name: RELEASE-NAME
            namespace: NAMESPACE
