---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: configMap names
templates:
  - base.yaml
values:
  - ../../../tests/overallValues.yaml
tests:
  - it: default should pass
    asserts:
      - containsDocument:
          kind: ConfigMap
        not: true

  - it: with disabled configMap should pass
    set:
      resources.configMaps.config.enabled: false
    asserts:
      - containsDocument:
          kind: ConfigMap
        not: true

  - it: with multiple configMap should pass
    set:
      resources:
        configMaps:
          config:
            enabled: true
            data:
              foo: bar
          secondary:
            enabled: true
    asserts:
      - documentSelector:
          path: metadata.name
          value: RELEASE-NAME-config
        isNotNullOrEmpty:
          path: metadata.name
      - documentSelector:
          path: metadata.name
          value: RELEASE-NAME-secondary
        isNotNullOrEmpty:
          path: metadata.name

  - it: default name should pass
    set:
      resources:
        configMaps:
          config:
            enabled: true
    documentSelector:
      path: kind
      value: ConfigMap
    asserts:
      - equal:
          path: metadata.name
          value: RELEASE-NAME-config

  - it: with nameOverride should pass
    set:
      resources:
        configMaps:
          config:
            enabled: true
            nameOverride: http
    documentSelector:
      path: kind
      value: ConfigMap
    asserts:
      - equal:
          path: metadata.name
          value: RELEASE-NAME-http
