---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: service values
templates:
  - base.yaml
values:
  - ../../../tests/overallValues.yaml
tests:
  - it: ports and services are enabled by default
    set:
      resources:
        services:
          second:
            type: ClusterIP
            controller: main
            ports:
              first:
                port: 80
    asserts:
      - documentSelector:
          path: metadata.name
          value: RELEASE-NAME-second
        notExists:
          path: spec.allocateLoadBalancerNodePorts

  - it: services can be disabled
    set:
      resources.services.main.enabled: false
    asserts:
      - containsDocument:
          kind: Service
        not: true

  - it: externalTrafficPolicy should pass for NodePort service
    set:
      resources:
        services:
          main:
            type: NodePort
            externalTrafficPolicy: Local
    documentSelector:
      path: kind
      value: Service
    asserts:
      - equal:
          path: spec.externalTrafficPolicy
          value: Local

  - it: externalTrafficPolicy should pass for LoadBalancer service
    set:
      resources:
        services:
          main:
            type: LoadBalancer
            externalTrafficPolicy: Local
    documentSelector:
      path: kind
      value: Service
    asserts:
      - equal:
          path: spec.externalTrafficPolicy
          value: Local

  - it: allocateLoadBalancerNodePorts can be set to true
    set:
      resources:
        services:
          main:
            type: LoadBalancer
            allocateLoadBalancerNodePorts: true
    documentSelector:
      path: kind
      value: Service
    asserts:
      - equal:
          path: spec.allocateLoadBalancerNodePorts
          value: true

  - it: allocateLoadBalancerNodePorts can be set to false
    set:
      resources:
        services:
          main:
            type: LoadBalancer
            allocateLoadBalancerNodePorts: false
    documentSelector:
      path: kind
      value: Service
    asserts:
      - equal:
          path: spec.allocateLoadBalancerNodePorts
          value: false
