---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: serviceAccount values
templates:
  - base.yaml
tests:
  - it: other SA and secret
    set:
      teamShortname: ep
      resources.serviceAccounts.other.enabled: true
    asserts:
      - documentSelector:
          path: kind
          value: ServiceAccount
        equal:
          path: metadata.name
          value: RELEASE-NAME-other
      - documentSelector:
          path: kind
          value: ServiceAccount
        equal:
          path: secrets
          value:
            - name: RELEASE-NAME-other-sa-token
      - documentSelector:
          path: kind
          value: Secret
        equal:
          path: metadata.name
          value: RELEASE-NAME-other-sa-token
      - documentSelector:
          path: kind
          value: Secret
        equal:
          path: metadata.annotations["kubernetes.io/service-account.name"]
          value: RELEASE-NAME-other


  - it: other SA and secret with nameOverride
    set:
      teamShortname: ep
      resources.serviceAccounts.other.nameOverride: second
    asserts:
      - documentSelector:
          path: kind
          value: ServiceAccount
        equal:
          path: metadata.name
          value: RELEASE-NAME-second
      - documentSelector:
          path: kind
          value: ServiceAccount
        equal:
          path: secrets
          value:
            - name: RELEASE-NAME-second-sa-token
      - documentSelector:
          path: kind
          value: Secret
        equal:
          path: metadata.name
          value: RELEASE-NAME-second-sa-token
      - documentSelector:
          path: kind
          value: Secret
        equal:
          path: metadata.annotations["kubernetes.io/service-account.name"]
          value: RELEASE-NAME-second
