# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Docker

on:
  push:
    paths:
      - base/**
      - .github/workflow/build-chart.yaml

jobs:
  push:
    runs-on: ubuntu-latest
    container: alpine/helm:3.17.2

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build/Push chart
        run: |
          bash -x bin/build.sh