---
# Source: base-template/templates/base.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: release-name
  labels:
    app: release-name
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name
    tags.datadoghq.com/version: "31"
    team: ep
spec:
  maxUnavailable: 10%
  selector:
    matchLabels:
      app.kubernetes.io/component: main
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: release-name
---
# Source: base-template/templates/base.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name
  labels:
    app: release-name
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name
    tags.datadoghq.com/version: "31"
    team: ep
secrets:
  - name: release-name-sa-token
---
# Source: base-template/templates/base.yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: release-name-sa-token
  labels:
    app: release-name
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name
    tags.datadoghq.com/version: "31"
    team: ep
  annotations:
    kubernetes.io/service-account.name: release-name
---
# Source: base-template/templates/base.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-name-config
  labels:
    app: release-name
    app.kubernetes.io/component: config
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name
    tags.datadoghq.com/version: "31"
    team: ep
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "pd-ssd"
---
# Source: base-template/templates/base.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-name-media
  labels:
    app: release-name
    app.kubernetes.io/component: media
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name
    tags.datadoghq.com/version: "31"
    team: ep
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "pd-ssd"
---
# Source: base-template/templates/base.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name
  labels:
    app: release-name
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    app.kubernetes.io/service: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name
    tags.datadoghq.com/version: "31"
    team: ep
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: release-name
---
# Source: base-template/templates/base.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name
  labels:
    app: release-name
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name
    tags.datadoghq.com/version: "31"
    team: ep
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 33%
  selector:
    matchLabels:
      app.kubernetes.io/component: main
      app.kubernetes.io/name: release-name
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        ad.datadoghq.com/main.checks: |
          {
            "openmetrics": {
              "init_config": {},
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:8080/metrics",
                  "namespace": "test",
                  "metrics": [
                    "^test.+"
                  ],
                  "collect_counters_with_distributions": true,
                  "max_returned_metrics": 20000
                },{
                  "openmetrics_endpoint": "http://%%host%%:8080/metrics",
                  "namespace": "zaez",
                  "metrics": [
                    "^aze.+"
                  ],
                  "collect_counters_with_distributions": true,
                  "max_returned_metrics": 20000
                }
              ]
            }
          }
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        sidecar.istio.io/proxyCPU: 100m
        sidecar.istio.io/proxyCPULimit: "1"
        sidecar.istio.io/proxyMemory: 200Mi
        sidecar.istio.io/proxyMemoryLimit: 1Gi
      labels:
        app: release-name
        app.kubernetes.io/component: main
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/name: release-name
        tags.datadoghq.com/service: release-name
        tags.datadoghq.com/version: "31"
        team: ep
    spec:
      enableServiceLinks: true
      serviceAccountName: release-name
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
      dnsPolicy: ClusterFirst
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.blabla.io/k8s-volatile
                operator: Exists
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - release-name
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - main
              topologyKey: kubernetes.io/hostname
            weight: 50
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: main
              app.kubernetes.io/instance: release-name
              app.kubernetes.io/name: release-name
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: main
              app.kubernetes.io/instance: release-name
              app.kubernetes.io/name: release-name
          maxSkew: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      tolerations:
        - effect: NoSchedule
          key: cloud.blabla.io/k8s-volatile
          operator: Equal
          value: "true"
      containers:
        - env:
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/service']
          - name: DD_TRACE_ENABLED
            value: "true"
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']
          image: ghcr.io/mendhak/http-https-echo:31
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: main
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            procMount: /dd
            readOnlyRootFilesystem: true
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 0
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /var/run/datadog
            name: dsdsocket
          - mountPath: /media
            name: media
          - mountPath: /test
            name: tests
            readOnly: true
          - mountPath: /tmp
            name: tmp
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - hostPath:
            path: /var/run/datadog
          name: dsdsocket
        - name: media
          persistentVolumeClaim:
            claimName: media
        - emptyDir: {}
          name: tmp
---
# Source: base-template/templates/base.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-second
  labels:
    app: release-name
    app.kubernetes.io/component: second
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name
    tags.datadoghq.com/version: "31"
    team: ep
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 33%
  selector:
    matchLabels:
      app.kubernetes.io/component: second
      app.kubernetes.io/name: release-name
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: release-name
        app.kubernetes.io/component: second
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/name: release-name
        tags.datadoghq.com/service: release-name
        tags.datadoghq.com/version: "31"
        team: ep
    spec:
      enableServiceLinks: true
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
      dnsPolicy: ClusterFirst
      containers:
        - image: ghcr.io/mendhak/http-https-echo:31
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: second
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 0
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /media
            name: media
          - mountPath: /test
            name: tests
            readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: media
          persistentVolumeClaim:
            claimName: media
---
# Source: base-template/templates/base.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: release-name
  labels:
    app: release-name
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name
    tags.datadoghq.com/version: "31"
    team: ep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: release-name
  minReplicas: 2
  maxReplicas: 50
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
---
# Source: base-template/templates/base.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-third
  labels:
    app: release-name
    app.kubernetes.io/component: third
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name
    tags.datadoghq.com/version: "31"
    team: ep
spec:
  revisionHistoryLimit: 3
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: third
      app.kubernetes.io/name: release-name
      app.kubernetes.io/instance: release-name
  serviceName: release-name
  template:
    metadata:
      annotations: 
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels: 
        app: release-name
        app.kubernetes.io/component: third
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/name: release-name
        tags.datadoghq.com/service: release-name
        tags.datadoghq.com/version: "31"
        team: ep
    spec: 
      enableServiceLinks: true
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
      dnsPolicy: ClusterFirst
      containers:
        - image: ghcr.io/mendhak/http-https-echo:31
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: second
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 0
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /media
            name: media
          - mountPath: /test
            name: tests
            readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: media
          persistentVolumeClaim:
            claimName: media
---
# Source: base-template/templates/base.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name
  labels:
    app: release-name
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name
    tags.datadoghq.com/version: "31"
    team: ep
spec:
  rules:
    - host: "toto.com"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: release-name
                port:
                  number: 8080
---
# Source: base-template/templates/base.yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: release-name-e2e-tests-one-app-test
  labels:
    app: release-name
    app.kubernetes.io/component: e2eTests
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name
    tags.datadoghq.com/version: "31"
    team: ep
spec:
  providerRef:
    name: e2e-tests-flux-hooks
  eventSources:
    - kind: HelmRelease
      name: release-name
  inclusionList:
    - ".*succeeded.*"
  eventMetadata:
    project: test
    slackChannel: '#toto'
    tags: tyty
    type: one-app
    version: "31"
---
# Source: base-template/templates/base.yaml
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: release-name
  labels:
    app: release-name
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    istio.io/tag: stable
    tags.datadoghq.com/service: release-name
    tags.datadoghq.com/version: "31"
    team: ep
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/component: main
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: release-name
  outboundTrafficPolicy:
    mode: "REGISTRY_ONLY"
  egress:
    - hosts:
      - istio-system/metadata.google.internal
      - istio-system/metadata.google.internal.
