---
# Source: base-template/templates/base.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-config
  labels:
    app: release-name
    app.kubernetes.io/component: config
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    team: ep
data:
  test: value 1
---
# Source: base-template/templates/base.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: release-name
  labels:
    app: release-name
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    team: ep
spec:
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 30
  timeZone: "UTC"
  schedule: "32 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 6
      template:
        metadata:
          annotations:
            checksum/configMaps: afdf20f511621d5cb358c5e8b0da2d14cdbe2549fb12fa123f6a6e9baabef26e
            cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          labels:
            app: release-name
            app.kubernetes.io/component: main
            app.kubernetes.io/instance: release-name
            app.kubernetes.io/name: release-name
            team: ep
        spec:
          enableServiceLinks: true
          automountServiceAccountToken: true
          securityContext:
            runAsNonRoot: true
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          containers:
            - image: ghcr.io/mendhak/http-https-echo:31
              imagePullPolicy: IfNotPresent
              name: main
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
