---
# Source: base-template/templates/base.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: release-name-titi
  labels:
    app: release-name
    app.kubernetes.io/component: titi
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name-titi
    tags.datadoghq.com/version: "43"
spec:
  maxUnavailable: 10%
  selector:
    matchLabels:
      app.kubernetes.io/component: titi
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: release-name
---
# Source: base-template/templates/base.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: release-name-toto
  labels:
    app: release-name
    app.kubernetes.io/component: toto
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name-toto
    tags.datadoghq.com/version: "42"
spec:
  maxUnavailable: 10%
  selector:
    matchLabels:
      app.kubernetes.io/component: toto
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: release-name
---
# Source: base-template/templates/base.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-titi
  labels:
    app: release-name
    app.kubernetes.io/component: titi
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name-titi
    tags.datadoghq.com/version: "43"
secrets:
  - name: release-name-titi-sa-token
---
# Source: base-template/templates/base.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-toto
  labels:
    app: release-name
    app.kubernetes.io/component: toto
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name-toto
    tags.datadoghq.com/version: "42"
secrets:
  - name: release-name-toto-sa-token
---
# Source: base-template/templates/base.yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: release-name-titi-sa-token
  labels:
    app: release-name
    app.kubernetes.io/component: titi
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
  annotations:
    kubernetes.io/service-account.name: release-name-titi
---
# Source: base-template/templates/base.yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: release-name-toto-sa-token
  labels:
    app: release-name
    app.kubernetes.io/component: toto
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
  annotations:
    kubernetes.io/service-account.name: release-name-toto
---
# Source: base-template/templates/base.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-titi
  labels:
    app: release-name
    app.kubernetes.io/component: titi
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    app.kubernetes.io/service: release-name-titi
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name-titi
    tags.datadoghq.com/version: "43"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: titi
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: release-name
---
# Source: base-template/templates/base.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-toto
  labels:
    app: release-name
    app.kubernetes.io/component: toto
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    app.kubernetes.io/service: release-name-toto
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name-toto
    tags.datadoghq.com/version: "42"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: toto
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: release-name
---
# Source: base-template/templates/base.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-titi
  labels:
    app: release-name
    app.kubernetes.io/component: titi
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name-titi
    tags.datadoghq.com/version: "43"
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 33%
  selector:
    matchLabels:
      app.kubernetes.io/component: titi
      app.kubernetes.io/name: release-name
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        sidecar.istio.io/proxyCPU: 100m
        sidecar.istio.io/proxyCPULimit: "1"
        sidecar.istio.io/proxyMemory: 200Mi
        sidecar.istio.io/proxyMemoryLimit: 1Gi
      labels:
        app: release-name
        app.kubernetes.io/component: titi
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/name: release-name
        tags.datadoghq.com/service: release-name-titi
        tags.datadoghq.com/version: "43"
    spec:
      enableServiceLinks: true
      serviceAccountName: release-name-titi
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
      dnsPolicy: ClusterFirst
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.blabla.io/k8s-volatile
                operator: Exists
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - release-name
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - titi
              topologyKey: kubernetes.io/hostname
            weight: 50
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: titi
              app.kubernetes.io/instance: release-name
              app.kubernetes.io/name: release-name
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: titi
              app.kubernetes.io/instance: release-name
              app.kubernetes.io/name: release-name
          maxSkew: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      tolerations:
        - effect: NoSchedule
          key: cloud.blabla.io/k8s-volatile
          operator: Equal
          value: "true"
      containers:
        - env:
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/service']
          - name: DD_TRACE_ENABLED
            value: "true"
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']
          image: test:43
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: main
          ports:
          - containerPort: 8080
            name: http
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 0
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /var/run/datadog
            name: dsdsocket
          - mountPath: /tmp
            name: tmp
      volumes:
        - hostPath:
            path: /var/run/datadog
          name: dsdsocket
        - emptyDir: {}
          name: tmp
---
# Source: base-template/templates/base.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-toto
  labels:
    app: release-name
    app.kubernetes.io/component: toto
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name-toto
    tags.datadoghq.com/version: "42"
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 33%
  selector:
    matchLabels:
      app.kubernetes.io/component: toto
      app.kubernetes.io/name: release-name
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        sidecar.istio.io/proxyCPU: 100m
        sidecar.istio.io/proxyCPULimit: "1"
        sidecar.istio.io/proxyMemory: 200Mi
        sidecar.istio.io/proxyMemoryLimit: 1Gi
      labels:
        app: release-name
        app.kubernetes.io/component: toto
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/name: release-name
        tags.datadoghq.com/service: release-name-toto
        tags.datadoghq.com/version: "42"
    spec:
      enableServiceLinks: true
      serviceAccountName: release-name-toto
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
      dnsPolicy: ClusterFirst
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.blabla.io/k8s-volatile
                operator: Exists
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - release-name
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - toto
              topologyKey: kubernetes.io/hostname
            weight: 50
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: toto
              app.kubernetes.io/instance: release-name
              app.kubernetes.io/name: release-name
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: toto
              app.kubernetes.io/instance: release-name
              app.kubernetes.io/name: release-name
          maxSkew: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      tolerations:
        - effect: NoSchedule
          key: cloud.blabla.io/k8s-volatile
          operator: Equal
          value: "true"
      containers:
        - env:
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/service']
          - name: DD_TRACE_ENABLED
            value: "true"
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']
          image: there:42
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: main
          ports:
          - containerPort: 8080
            name: http
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 0
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /var/run/datadog
            name: dsdsocket
          - mountPath: /tmp
            name: tmp
      volumes:
        - hostPath:
            path: /var/run/datadog
          name: dsdsocket
        - emptyDir: {}
          name: tmp
---
# Source: base-template/templates/base.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: release-name-titi
  labels:
    app: release-name
    app.kubernetes.io/component: titi
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name-titi
    tags.datadoghq.com/version: "43"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: release-name-titi
  minReplicas: 2
  maxReplicas: 50
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
---
# Source: base-template/templates/base.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: release-name-toto
  labels:
    app: release-name
    app.kubernetes.io/component: toto
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    tags.datadoghq.com/service: release-name-toto
    tags.datadoghq.com/version: "42"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: release-name-toto
  minReplicas: 2
  maxReplicas: 50
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
---
# Source: base-template/templates/base.yaml
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: release-name-titi
  labels:
    app: release-name
    app.kubernetes.io/component: titi
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    istio.io/tag: stable
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/component: titi
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: release-name
  outboundTrafficPolicy:
    mode: "REGISTRY_ONLY"
  egress:
    - hosts:
      - istio-system/metadata.google.internal
      - istio-system/metadata.google.internal.
---
# Source: base-template/templates/base.yaml
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: release-name-toto
  labels:
    app: release-name
    app.kubernetes.io/component: toto
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-name
    helm.sh/chart: base-template-0.0.0
    istio.io/tag: stable
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/component: toto
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: release-name
  outboundTrafficPolicy:
    mode: "REGISTRY_ONLY"
  egress:
    - hosts:
      - istio-system/metadata.google.internal
      - istio-system/metadata.google.internal.
