# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Base builder

on:
  push:
    paths:
      - docker/base-builder/**
      - .github/workflows/base-builder.yaml

jobs:
  builder:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build/Push image
        run: |
          branch=${GITHUB_REF##*/}
          if [ "$branch" == "main" ]; then
            export PUSH=true
          else
            FIRST_COMMIT_IN_BRANCH=$(git log --pretty=format:%H origin/master.. | tail -1)
            export COMMIT=$(git log -1 --pretty=format:%H ${FIRST_COMMIT_IN_BRANCH}^)
          fi
          cd docker/base-builder
          ../../bin/docker-build.sh
