# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Base

on:
  push:
    paths:
      - base/**
      - .github/workflows/build-chart.yaml
      - bin/chart-build.sh

jobs:
  push:
    runs-on: ubuntu-latest
    container: ghcr.io/n0rad/base-builder:1.250327.1105-H81dd083

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build/Push chart
        run: |
          export HOME=/root # stupid github action container changing home

          cd base
          ../bin/chart-build.sh
